config/routes.rb
Netwctools::Application.routes.draw do
  resources :domains do
		member do
			get 'rezervrangevlan'
			post 'genfromrange'
		end
	end

	resources :vlans, :only => [:index, :destroy, :edit] do
		collection do
			get 'dispvlans'
			get 'allvlans'
			get 'rangecreate'
			get 'dispvlans'
			get 'autocreate'
			post 'autocreate2'
		end
		member do
			get 'createbd'
		end
	end
			

  resources :myusers

  post "tpvlans/:id" => 'terminate_points#tpvlans'
  post "vinovlans/:id" => 'vinos#vinovlans'

  resources :vinos, :except => :show

  resources :terminate_points, :except => [:show]

  resources :swmodels, :except => [:new]
  resources :switches, :except => [:new, :edit]
  resources :ips, :except => :new

  get "networks" => 'networks#index'
  post "networks" => 'networks#create'
  get "networks/findipfromallnet" => 'networks#findallnetsw'
  delete "networks/:id" => 'networks#destroy'
  get "networks/:id" => 'networks#findsw'

end

app/models/vlan.rb
class Vlan < ActiveRecord::Base
	has_many :subvlans, :class_name => "Vlan", :foreign_key => "bridgedomain_id"
	belongs_to :bridgedomain, :class_name => "Vlan", :foreign_key => "bridgedomain_id"

	belongs_to :vino
	has_one :terminate_point, :through => :vino 
	belongs_to :domain

	def getvino
		self.bridgedomain.vino
	end

end

app/controllers/vlans_controller.rb
class VlansController < ApplicationController
  layout 'vlansupmenu'

	def index
		@myusers=Myuser.all
		@domains=Domain.all
	end

	def createbd
		@vlan=Vlan.find(params[:id])
		@vlan.used=true
		@vlan.canbebd=true
		@vlan.save
		redirect_to :back
	end

	def dispvlans
		#@user=params.has_key?(:user) ? params[:user] : nil
		@domain=params.has_key?(:domains) ? Domain.find(params[:domains]) : nil
		@used=params.has_key?(:used) ? (params[:used]=='true' ? true : false) : true
		@showbds=params.has_key?(:showbds) ? params[:showbds] : Hash.new

		#@vlans=(@domain!=nil ? Domain.find(@domain).vlans : Vlan.all)
		
		@vlans=Array.new
		if @domain!=nil and @used==true
			#@domain.terminate_points.each{|tp|
			#	tp.vlans.each{|vlan|@vlans.push(vlan)}
			#}
			@vlans=@domain.vlans
		elsif @domain!=nil
			@vlans=@domain.vlans
		else
			@vlans=Vlan.all
		end
		@bds=@vlans
		@bds=@bds.find_all{|bd|bd.canbebd==true}
		@vlans.find_all{|vlan|vlan.used==@used}
	end

	def rangecreate
		#@range=Rangevlan.new
		@vlans=Vlan.all
		@vinos=Vino.all
	end

	def genfromrange
		@range=Rangevlan.new
		@range.range=params[:range]
		@range.vino_id=params[:vino_id]
		if @range.isrange? and @range.notexistvlans?
			@range.createvlansindb
			redirect_to vlans_path
		else
			redirect_to :back
		end
	end

  def autocreate
		@domain=Domain.find(params[:domain_id])
    @bds=@domain.vlans.find_all_by_canbebd(true)
  end

  def autocreate2
    #@vino=Vino.find(params[:vino_id])
		@domain=Domain.find(params[:domain_id])
    @bd=Vlan.find(params[:bd_id]) if params[:bd_id] != ""
    @freevlan=@domain.freevlan
    @freevlan.used=true
    if params[:bd_id] != ""
      @freevlan.bridgedomain=@bd
      @freevlan.canbebd=false
    else
      @freevlan.canbebd=true
    end
    @freevlan.save
  end

  def manualcreate
  end

  def destroy
		@vlan=Vlan.find(params[:id])
		@vlan.destroy
		redirect_to :back
  end

  def edit
  end

	def vlanbdon
		@vlan=Vlan.find(params[:id])
		@vlan.canbebd=true
		@vlan.save
		redirect_to :back
	end

	def vlanbdoff
		@vlan=Vlan.find(params[:id])
		@vlan.canbebd=false
		@vlan.save
		redirect_to :back
	end

	def changebd
		@vlan=Vlan.find(params[:id])
		@bds=Vlan.find_all_by_canbebd(true)
	end

	def changebdn
		@vlan=Vlan.find(params[:id])
		@vlan.bridgedomain_id=params[:bd_id]
		@vlan.save
		redirect_to vlans_path
	end
end

app/helpers/vlans_helper.rb
module VlansHelper
end

app/views/vlans/_dispbds.html.erb
<% @bds.each do |bd| %>
	<h3 style='display:inline'>
		<%= bd.vlanpvid %>
	</h3>
	Вынос: 
	<%#= bd.vino.vinosname if bd.vino!=nil %>
	<%= bd.vino!=nil ? bd.vino.vinosname : "_Присвоить_" %>
	Точка терминирования: 
	<%=  bd.terminate_point!=nil ? bd.terminate_point.routerip : "_Присвоить_" %>
	<% if @showbds.has_key?(bd.vlanpvid.to_s) %>
		<% if @showbds[bd.vlanpvid.to_s]=='true' %>
			<%= 'true' %>
			<%= link_to '-', dispvlans_vlans_path(:showbds => {bd.vlanpvid.to_s => false}.merge(@showbds){|key,oldval,newval|oldval}, used:@used, :domains => @domain) %>
		<% else %>
			<%= 'false' %>
			<%= link_to '+', dispvlans_vlans_path(:showbds => {bd.vlanpvid.to_s => true}.merge(@showbds){|key,oldval,newval|oldval}, used:@used, :domains => @domain) %>
		<% end -%>
	<% else %>
		<%='net voobshe' %>
		<%= link_to '+', dispvlans_vlans_path(:showbds => {bd.vlanpvid.to_s => true}.merge(@showbds), used:@used, :domains => @domain) %>
	<% end -%>
			
	<% @showvlans=bd.subvlans %>
	<br />
	<%= render :partial => 'tableofvlans' if @showbds[bd.vlanpvid.to_s]=='true' %>
<% end -%>

app/views/vlans/_displayvlans.html.erb
<h1>Отображение Вланов</h1>
<nav>
	<%= render :partial => 'menuused' %>
  <div>
    <h3>
      <% Myuser.all.each do |myuser| %>
        <%= link_to myuser.name, request.path+'?myuser='+myuser.name %>
      <% end -%>
    </h3>
  </div>
</nav>
<% if @used==true %>
	<%= render :partial => 'dispbds' %>
<% else %>
  <% @vlans=Vlan.all %>
  <%= render :partial => 'tableofvlans' %>
<% end -%>

app/views/vlans/_tableofvlans.html.erb
<table>
	<tr>
		<th>Влан PVID</th>
		<% if @used %>
			<th>Адреса на которых используется</th>
			<th>Примечание</th>
		<% end -%>
		<%# Еще добавить ответственного, когда создан %>
	</tr>
	<% @showvlans.each do |vlan| -%>
		<% if vlan.used==@used %>
			<tr>
				<td><%= vlan.vlanpvid %></td>
				<% if @used %>
					<td><%= vlan.address %></td>
					<td><%= vlan.descr %></td>
					<td><%#= vlan.vino.vinosname %></td>
					<td><%#= vlan.vino.terminate_point.routerip %></td>
					<td>
						<%= link_to "Освободить влан", "vlan/#{vlan.id}" %>
						<%= link_to "Редактировать влан", "vlan/#{vlan.id}", :method => :get %>
					</td>
				<% else %>
					<td>
						<%= link_to "Убрать влан из резерва", vlan_path(:id => vlan.id), :method => :delete %>
						<%= link_to "Выделить под bd", createbd_vlan_path(vlan) %>
					</td>
				<% end -%>
			</tr>
		<% end -%>
	<% end -%>
</table>

app/views/vlans/allvlans.html.erb
<h1>Таблица вланов</h1>
<table>
	<tr>
		<th>Влан PVID</th>
		<th>Используется</th>
		<th>Адреса на которых используется</th>
		<th>Примечание</th>
		<th>Вынос</th>
		<th>Терминируется на</th>
		<th>Может быть BD</th>
		<th>Bridge Domain</th>
		<%# Еще добавить ответственного, когда создан %>
	</tr>
	<% @vlans.each do |vlan| -%>
		<tr>
			<td><%= vlan.vlanpvid %></td>
			<td><%= vlan.used %></td>
			<td><%= vlan.address %></td>
			<td><%= vlan.descr %></td>
			<td><%= vlan.vino.vinosname %></td>
			<td><%= vlan.vino.terminate_point.routerip %></td>
			<td>
				<% if vlan.canbebd!=true %>
					<%= link_to "bd on", "vlanbdon/#{vlan.id}", :method => :get %>
				<% else %>
					<%= link_to "bd off", "vlanbdoff/#{vlan.id}", :method => :get %>
				<% end -%>
			</td>
			<td>
				<%= vlan.bridgedomain.vlanpvid if vlan.bridgedomain %>
				<%= link_to "Сменить", "changebd/#{vlan.id}", :method => :get %>
			</td>
			<td>
				<%= link_to "Удалить влан", "vlan/#{vlan.id}", :method => :delete %>
				<%= link_to "Редактировать влан", "vlan/#{vlan.id}", :method => :get %>
			</td>
		</tr>
	<% end -%>
</table>

app/views/vlans/autocreate.html.erb
<h1>Введите информацию для автоматического выделения влана</h1>
<%= form_tag autocreate2_vlans_path(:domain_id => @domain.id), :method => :post do %>
  <%= label_tag :bd, "Бридж домайн" %><br />
  <%= select_tag :bd_id, options_from_collection_for_select(@bds, :id, :vlanpvid), :include_blank => true %><br />
  <%= submit_tag "Зарезервировать влан автоматически" %><br />
<% end -%>

app/views/vlans/autocreate2.html.erb
<h1>Autocreate 2 rezults</h1>
<div><%= @vino %></div>
<div><%= @bd %></div>
<div><%= @freevlan %></div>
<%= button_to "На страницу вланов", vlans_path, :method => :get %>

app/views/vlans/changebd.html.erb
<h1>Выберите bridge-domain</h1>
<%= form_tag "/changebdn", :method => :post do %>
	<%= hidden_field_tag :id, @vlan.id %>
	<%= label_tag :bd_id, "Бридж домайн" %>
	<%= select_tag :bd_id, options_from_collection_for_select(@bds, :id, :vlanpvid) %><br />
	<%= submit_tag "Сменить Бридж Домайн" %>
<% end -%>

app/views/vlans/dispvlans.html.erb
<% choosestyle="background: lightblue" %>
<nav>
<% Domain.all.each do |domain| %>
	<% if domain.id==@domain.id %>
		<% domainstyle=choosestyle %>
	<% else %>
		<% domainstyle="" %>
	<% end -%>
	<%= link_to domain.name, dispvlans_vlans_path(:domains => domain.id, used:@used), :style => domainstyle %>
<% end -%>
<br />
<% linkfreestyle=Hash.new %>
<%# linkfreestyle[:free]="" %>
<%# linkfreestyle[:used]=choosestyle %>
<% if @used==true %>
	<% linkfreestyle[:free]="" %>
	<% linkfreestyle[:used]=choosestyle %>
<% else %>
	<% linkfreestyle[:free]=choosestyle %>
	<% linkfreestyle[:used]="" %>
<% end %>
<%= link_to 'Занятые Вланы', dispvlans_vlans_path(:showbds => {}.merge(@showbds), used:true, :domains => @domain), :style=>linkfreestyle[:used] %>
<%= link_to 'Свободные Вланы', dispvlans_vlans_path(:showbds => {}.merge(@showbds), used:false, :domains => @domain), :style=>linkfreestyle[:free] %>
</nav>
<%#= @domain %>
<%#= @vlans %>
<%#= @used %>
<% if @used==true %>
	<%= render :partial => 'dispbds' %>
<% else %>
	<% @showvlans=@vlans %>
  <%= render :partial => 'tableofvlans' %>
	<%#= "net" %>
<% end -%>

app/views/vlans/edit.html.erb
<h1>Vlans#edit</h1>
<p>Find me in app/views/vlans/edit.html.erb</p>

app/views/vlans/index.html.erb
<%= link_to 'Создать нового пользователя', new_myuser_path %><br />
<% @myusers.each do |myuser| %>
	<h3>
		<%= myuser.name %>    
		<%= link_to "Удалить пользователя", myuser_path(myuser), :method => :delete %>    
		<%= link_to "Добавить домен", new_domain_path(:myuser_id => myuser.id) %>
	</h3>
	<% myuser.domains.each do |domain| %>
		<h3 style='display:inline'><%= link_to domain.name, dispvlans_vlans_path(:domains => domain.id)%></h3>
		<%= "Домен глобальный" if domain.globaly %>
		<%= link_to "Выдать новый Влан (авт.)", autocreate_vlans_path(:domain_id => domain.id) %>
		<%= link_to "Добавить свободных вланов", rezervrangevlan_domain_path(domain) %>
		<%= link_to "Удалить домен", domain_path(domain), :method => :delete %>
		<%= link_to :Редактировать, edit_domain_path(domain, :myuser_id => myuser.id) %>
		<br />
		<%= domain.descr %>
	<% end if myuser.domains!=nil -%>
<% end if @myusers!=nil -%>

app/views/vlans/manualcreate.html.erb
<h1>Vlans#manualcreate</h1>
<p>Find me in app/views/vlans/manualcreate.html.erb</p>

app/views/vlans/rangecreate.html.erb
<h1>Зарезервировать диапозон вланов</h1>
<%= form_tag 'genfromrange', :method => :post do %>
	<%= label_tag :range, "Диапозон вланов" %>
	<%= text_field_tag :range %><br />
	<%= label_tag :vino_id, "Вынос" %>
	<%= select_tag :vino_id, options_from_collection_for_select(@vinos, :id, :vinosname) %><br />
	<%= submit_tag "Сгенерировать вланы" %><br />
<% end -%>