config/routes.rb
Netwctools::Application.routes.draw do
  resources :domains do
		member do
			get 'rezervrangevlan'
			post 'genfromrange'
		end
	end

	resources :vlans, :only => [:index, :destroy, :edit] do
		collection do
			get 'dispvlans'
			get 'allvlans'
			get 'rangecreate'
			get 'dispvlans'
			get 'autocreate'
			post 'autocreate2'
		end
		member do
			get 'createbd'
		end
	end
			

  resources :myusers

  post "tpvlans/:id" => 'terminate_points#tpvlans'
  post "vinovlans/:id" => 'vinos#vinovlans'

  resources :vinos, :except => :show

  resources :terminate_points, :except => [:show]

  resources :swmodels, :except => [:new]
  resources :switches, :except => [:new, :edit]
  resources :ips, :except => :new

  get "networks" => 'networks#index'
  post "networks" => 'networks#create'
  get "networks/findipfromallnet" => 'networks#findallnetsw'
  delete "networks/:id" => 'networks#destroy'
  get "networks/:id" => 'networks#findsw'

end

app/models/myuser.rb
class Myuser < ActiveRecord::Base
	has_and_belongs_to_many :domains #correct this to has_and_belongs_to_many
end

app/controllers/myusers_controller.rb
class MyusersController < ApplicationController
  # GET /myusers
  # GET /myusers.json
  def index
    @myusers = Myuser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @myusers }
    end
  end

  # GET /myusers/1
  # GET /myusers/1.json
  def show
    @myuser = Myuser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @myuser }
    end
  end

  # GET /myusers/new
  # GET /myusers/new.json
  def new
    @myuser = Myuser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @myuser }
    end
  end

  # GET /myusers/1/edit
  def edit
    @myuser = Myuser.find(params[:id])
  end

  # POST /myusers
  # POST /myusers.json
  def create
    @myuser = Myuser.new(params[:myuser])

    respond_to do |format|
      if @myuser.save
        format.html { redirect_to vlans_path, notice: 'Myuser was successfully created.' }
        format.json { render json: @myuser, status: :created, location: @myuser }
      else
        format.html { render action: "new" }
        format.json { render json: @myuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /myusers/1
  # PUT /myusers/1.json
  def update
    @myuser = Myuser.find(params[:id])

    respond_to do |format|
      if @myuser.update_attributes(params[:myuser])
        format.html { redirect_to @myuser, notice: 'Myuser was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @myuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myusers/1
  # DELETE /myusers/1.json
  def destroy
    @myuser = Myuser.find(params[:id])
		respond_to do |format|
			if @myuser.domains.empty?
				@myuser.destroy
				format.html {redirect_to :back, notice: "User deleted" }
				format.json {head :ok}
			else
				format.html {redirect_to :back, alert: "Can't delete, try del all domains for this user"}
				format.json {render json: @myuser.errors, status: :unprocessable_entity }
			end
		end

  end
end

app/helpers/myusers_helper.rb
module MyusersHelper
end

app/views/myusers/_form.html.erb
<%= form_for(@myuser) do |f| %>
  <% if @myuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myuser.errors.count, "error") %> prohibited this myuser from being saved:</h2>

      <ul>
      <% @myuser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myusers/edit.html.erb
<h1>Editing myuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @myuser %> |
<%= link_to 'Back', myusers_path %>

app/views/myusers/index.html.erb
<h1>Listing myusers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @myusers.each do |myuser| %>
  <tr>
    <td><%= myuser.name %></td>
    <td><%= link_to 'Show', myuser %></td>
    <td><%= link_to 'Edit', edit_myuser_path(myuser) %></td>
    <td><%= link_to 'Destroy', myuser, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Myuser', new_myuser_path %>

app/views/myusers/new.html.erb
<h1>New myuser</h1>

<%= render 'form' %>

<%= link_to 'Back', myusers_path %>

app/views/myusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @myuser.name %>
</p>


<%= link_to 'Edit', edit_myuser_path(@myuser) %> |
<%= link_to 'Back', myusers_path %>