config/routes.rb
Netwctools::Application.routes.draw do
  resources :domains do
		member do
			get 'rezervrangevlan'
			post 'genfromrange'
		end
	end

	resources :vlans, :only => [:index, :destroy, :edit] do
		collection do
			get 'dispvlans'
			get 'allvlans'
			get 'rangecreate'
			get 'dispvlans'
			get 'autocreate'
			post 'autocreate2'
		end
		member do
			get 'createbd'
		end
	end
			

  resources :myusers

  post "tpvlans/:id" => 'terminate_points#tpvlans'
  post "vinovlans/:id" => 'vinos#vinovlans'

  resources :vinos, :except => :show

  resources :terminate_points, :except => [:show]

  resources :swmodels, :except => [:new]
  resources :switches, :except => [:new, :edit]
  resources :ips, :except => :new

  get "networks" => 'networks#index'
  post "networks" => 'networks#create'
  get "networks/findipfromallnet" => 'networks#findallnetsw'
  delete "networks/:id" => 'networks#destroy'
  get "networks/:id" => 'networks#findsw'

end

app/models/domain.rb
class Domain < ActiveRecord::Base

	has_and_belongs_to_many :myusers #correct this to has_and_belongs_to_many
	has_many :vlans
	has_many :terminate_points 

	def freevlan
		self.vlans.find_by_used(false)
	end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
	layout 'vlansupmenu'

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @domains }
    end
  end

	def rezervrangevlan 
		@domain=Domain.find(params[:id])
	end

	def genfromrange
		@range=Rangevlan.new
		@range.range=params[:range]
		@range.domain_id=params[:id]
		if @range.isrange? and @range.notexistvlans?
			@range.createvlansindb
			redirect_to vlans_path
		else
			redirect_to :back
		end
  end

  # GET /domains/new
  # GET /domains/new.json
  def new
    @domain = Domain.new
		@myuser=Myuser.find(params[:myuser_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @domain }
    end
  end

  # GET /domains/1/edit
  def edit
    @domain = Domain.find(params[:id])
		@myusers = Myuser.all
		@myuser = Myuser.find(params[:myuser_id])
  end

  # POST /domains
  # POST /domains.json
  def create
		@myuser=Myuser.find(params[:myuser_id])
    @domain = Domain.new(params[:domain])
		@domain.myusers<<@myuser

    respond_to do |format|
      if @domain.save
        format.html { redirect_to vlans_path, notice: 'Domain was successfully created.' }
        format.json { render json: @domain, status: :created, location: @domain }
      else
        format.html { render action: "new" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /domains/1
  # PUT /domains/1.json
  def update
    @domain = Domain.find(params[:id])

    respond_to do |format|
      if @domain.update_attributes(params[:domain])
        format.html { redirect_to vlans_path, notice: 'Domain was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy
    respond_to do |format|
			if @domain.terminate_points.size != 0 
				format.html { redirect_to vlans_url }
				format.json { head :ok }
			else
				format.html { redirect_to :back, notice: "Can't delete, before delete terminate points"}
				format.json { render json: @domain.errors, status: :unprocessable_entity }
			end
    end
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_for @domain, :url => domains_path(:myuser_id => @myuser.id), :method => :post do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Имя %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Примечание %><br />
    <%= f.text_field :descr %>
  </div>
	<div class="field">
		<%= f.check_box :globaly %>
		<%= f.label :Глобальный %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Редактирование домена</h1>

<%= render 'form' %>

<%= link_to 'Назад', vlans_path %>

app/views/domains/index.html.erb
<h1>Listing domains</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Descr</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @domains.each do |domain| %>
  <tr>
    <td><%= domain.name %></td>
    <td><%= domain.descr %></td>
    <td><%= link_to 'Show', domain %></td>
		<td><%= link_to 'Edit', edit_domain_path(domain, :myuser_id => @myuser.id) %></td>
    <td><%= link_to 'Destroy', domain, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Domain', new_domain_path %>

app/views/domains/new.html.erb
<h1>Новый домен вланов</h1>

<%= render 'form' %>

<%= link_to :Назад, vlans_path %>

app/views/domains/rezervrangevlan.html.erb
<h1>Зарезервировать диапозон вланов</h1>
<%= form_tag 'genfromrange', :id => @domain.id, :method => :post do %>
	<%= label_tag :range, "Диапозон вланов" %>
	<%= text_field_tag :range %><br />
	<%= submit_tag "Зарезервировать" %><br />
<% end -%>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @domain.name %>
</p>

<p>
  <b>Descr:</b>
  <%= @domain.descr %>
</p>



<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>