config/routes.rb
Netwctools::Application.routes.draw do
  resources :domains do
		member do
			get 'rezervrangevlan'
			post 'genfromrange'
		end
	end

	resources :vlans, :only => [:index, :destroy, :edit] do
		collection do
			get 'dispvlans'
			get 'allvlans'
			get 'rangecreate'
			get 'dispvlans'
			get 'autocreate'
			post 'autocreate2'
		end
		member do
			get 'createbd'
		end
	end
			

  resources :myusers

  post "tpvlans/:id" => 'terminate_points#tpvlans'
  post "vinovlans/:id" => 'vinos#vinovlans'

  resources :vinos, :except => :show

  resources :terminate_points, :except => [:show]

  resources :swmodels, :except => [:new]
  resources :switches, :except => [:new, :edit]
  resources :ips, :except => :new

  get "networks" => 'networks#index'
  post "networks" => 'networks#create'
  get "networks/findipfromallnet" => 'networks#findallnetsw'
  delete "networks/:id" => 'networks#destroy'
  get "networks/:id" => 'networks#findsw'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Netwctools</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #EEEEEE;">
<nav><%= link_to "Главная", "/index" %>
<%= link_to "Подсети", "/networks" %>
<%= link_to "Модели свитчей", "/swmodels" %>
<%= link_to "Коммутаторы", "/switches" %>
<%= link_to "Вланы", "/vlans" %></nav>

<%# yield %>
<div id="content"><%= content_for?(:content) ? yield(:content) : yield %></div>

</body>
</html>

app/views/layouts/terminatepoints.html.erb
<% content_for :content do %>
  <nav><%= link_to "lala", terminate_points_path %></nav>
  <%= yield %>
<% end -%>
<%= render :template => 'layouts/application' %>

app/views/layouts/vlansupmenu.html.erb
<% content_for :content do %>
  <nav>
    <%= link_to "Вланы", vlans_path %>
    <%#= link_to "Все вланы", allvlans_vlans_path %>
    <%= link_to "Точки терминирования", terminate_points_path %>
    <%= link_to "Выносы", vinos_path %>
    <%#= link_to "Резерв. диапозона вланов", rangecreate_vlans_path %>
    <%#= link_to "Выдать влан", autocreate_vlans_path %>
  </nav>
	<h1>Вланы ДДС</h1>
  <%= yield %>
<% end -%>
<%= render :template => 'layouts/application' %>